MSM : MSM_main.o Medicine.o report.o
	gcc -o MSM MSM_main.o Medicine.o report.o
MSM_main.o : MSM_main.c
	gcc -c MSM_main.c
Medicine.o : Medicine.c 
	gcc -c Medicine.c
report.o : report.c
	gcc -c report.c
